server:
  port: 8100

spring:
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    # 数据库 1
    dbo:
      url: jdbc:mysql://127.0.0.1:18012/jpa_mp_one?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
      username: root
      password: root@Can10
      driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库 2
    dbt:
      url: jdbc:mysql://127.0.0.1:18012/jpa_mp_two?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
      username: root
      password: root@Can10
      driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    show-sql: false
    hibernate:
      format_sql: true
      primary-dialect: org.hibernate.dialect.MySQL55Dialect
      second-dialect: org.hibernate.dialect.MySQL55Dialect